# main battery
CONFIG_ZMK_BATTERY_REPORTING=y

# nice!view
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y 

#nice!view widgets
## general
CONFIG_NICE_EPAPER_ON=y
CONFIG_NICE_OLED_SHOW_SLEEP_ART_ON_IDLE=n
CONFIG_NICE_OLED_SHOW_SLEEP_ART_ON_SLEEP=n
## Peripheral
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_SMART_BATTERY=y 
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT=n 
